# Generated by Django 5.0.2 on 2024-06-29 05:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BedGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('isolated', models.BooleanField(default=False)),
                ('protected', models.BooleanField(default=False)),
                ('field_orientation', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('compass_orientation', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('length', models.FloatField()),
                ('width', models.FloatField()),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='beds.bedgroup')),
            ],
        ),
        migrations.CreateModel(
            name='Planting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.FloatField()),
                ('width', models.FloatField()),
                ('row_spacing', models.IntegerField()),
                ('plant_spacing', models.IntegerField()),
                ('sown_date', models.DateField(blank=True, null=True)),
                ('transplanted_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beds.bed')),
                ('previous_planting', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='beds.planting')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Row',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('alias', models.CharField(max_length=50)),
                ('plant_count', models.IntegerField()),
                ('planting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beds.planting')),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.IntegerField()),
                ('harvest_date', models.DateField()),
                ('removed_date', models.DateField()),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beds.row')),
            ],
        ),
    ]
