# Generated by Django 5.0.2 on 2024-03-27 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bed',
            name='length',
            field=models.FloatField(default=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bed',
            name='width',
            field=models.FloatField(default=1.2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='planting',
            name='plant_spacing',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='planting',
            name='row_spacing',
            field=models.IntegerField(),
        ),
    ]
