# Generated by Django 5.1.4 on 2024-12-22 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bed',
            name='origin_x',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bed',
            name='origin_y',
            field=models.FloatField(default=0),
        ),
    ]
