# Generated by Django 5.1.4 on 2024-12-24 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beds', '0002_bed_origin_x_bed_origin_y'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Plot',
            new_name='Field',
        ),
        migrations.AlterField(
            model_name='bed',
            name='length',
            field=models.FloatField(help_text='Length of the bed in metres'),
        ),
        migrations.AlterField(
            model_name='bed',
            name='width',
            field=models.FloatField(help_text='Width of the bed in metres'),
        ),
    ]
