# Generated by Django 5.0.2 on 2024-03-27 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beds', '0002_bed_length_bed_width_alter_planting_plant_spacing_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='row',
            old_name='bed',
            new_name='planting',
        ),
        migrations.AddField(
            model_name='row',
            name='alias',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
