# Generated by Django 5.0.2 on 2024-03-27 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beds', '0003_rename_bed_row_planting_row_alias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planting',
            name='sown_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='planting',
            name='transplanted_date',
            field=models.DateField(blank=True),
        ),
    ]
