# Generated by Django 5.0.2 on 2024-03-27 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beds', '0004_alter_planting_sown_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planting',
            name='sown_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planting',
            name='transplanted_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
