# Generated by Django 5.1.4 on 2024-12-30 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beds', '0005_relate_bed_group_to_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bed',
            old_name='origin_x',
            new_name='bedgroup_x',
        ),
        migrations.RenameField(
            model_name='bed',
            old_name='origin_y',
            new_name='bedgroup_y',
        ),
        migrations.AddField(
            model_name='bedgroup',
            name='field_x',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bedgroup',
            name='field_y',
            field=models.FloatField(default=0),
        ),
    ]
