# Generated by Django 5.1.4 on 2024-12-30 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beds', '0006_rename_x_y_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bed',
            old_name='bed_group',
            new_name='bedgroup',
        ),
    ]
