# Generated by Django 5.1.4 on 2025-01-16 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beds', '0007_rename_bedgroup_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bed',
            name='bedgroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='beds.bedgroup'),
        ),
    ]
